import {
  CompetitionTemplate,
  CompetitionTemplateKey,
  StatisticsRegistryItem,
} from '@/types';

export const STATISTICS_REGISTRY: StatisticsRegistryItem[] = [
  { key: 'points', label: 'Points', category: 'input', calculation_type: null },
  { key: 'wins', label: 'Wins', category: 'input', calculation_type: null },
  { key: 'draws', label: 'Draws', category: 'input', calculation_type: null },
  { key: 'losses', label: 'Losses', category: 'input', calculation_type: null },
  { key: 'goals_for', label: 'Goals For', category: 'input', calculation_type: null },
  { key: 'goals_against', label: 'Goals Against', category: 'input', calculation_type: null },
  { key: 'points_scored', label: 'Points Scored', category: 'input', calculation_type: null },
  { key: 'points_allowed', label: 'Points Allowed', category: 'input', calculation_type: null },
  { key: 'sets_won', label: 'Sets Won', category: 'input', calculation_type: null },
  { key: 'sets_lost', label: 'Sets Lost', category: 'input', calculation_type: null },
  { key: 'kills', label: 'Kills', category: 'input', calculation_type: null },
  { key: 'deaths', label: 'Deaths', category: 'input', calculation_type: null },
  { key: 'runs', label: 'Runs', category: 'input', calculation_type: null },
  { key: 'runs_allowed', label: 'Runs Allowed', category: 'input', calculation_type: null },
  { key: 'frames_won', label: 'Frames Won', category: 'input', calculation_type: null },
  { key: 'frames_lost', label: 'Frames Lost', category: 'input', calculation_type: null },
  { key: 'played', label: 'Played', category: 'derived', calculation_type: 'played' },
  { key: 'goal_difference', label: 'Goal Difference', category: 'derived', calculation_type: 'goal_difference' },
  { key: 'point_difference', label: 'Point Difference', category: 'derived', calculation_type: 'point_difference' },
  { key: 'set_difference', label: 'Set Difference', category: 'derived', calculation_type: 'set_difference' },
  { key: 'win_percentage', label: 'Win Percentage', category: 'derived', calculation_type: 'win_percentage' },
  { key: 'average_points', label: 'Average Points', category: 'derived', calculation_type: 'average_points' },
  { key: 'kill_death_ratio', label: 'Kill/Death Ratio', category: 'derived', calculation_type: 'kill_death_ratio' },
];

function template(
  key: CompetitionTemplateKey,
  override: Partial<CompetitionTemplate>
): CompetitionTemplate {
  return {
    key,
    label: override.label || key,
    description: override.description || '',
    competition_type: override.competition_type || 'sports',
    entity_type: override.entity_type || 'team',
    supports_draws: override.supports_draws ?? false,
    score_label: override.score_label || 'Score',
    scored_stat_key: override.scored_stat_key || 'points_scored',
    allowed_stat_key: override.allowed_stat_key || 'points_allowed',
    default_points_for_win: override.default_points_for_win ?? 1,
    default_points_for_draw: override.default_points_for_draw ?? 0,
    default_points_for_loss: override.default_points_for_loss ?? 0,
    statistic_keys: override.statistic_keys || ['wins', 'losses', 'points', 'played'],
    standings_column_keys: override.standings_column_keys || ['played', 'wins', 'losses', 'points'],
    ranking_rules: override.ranking_rules || [
      { criterion_type: 'statistic', statistic_key: 'points', label: 'Points', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  };
}

export const COMPETITION_TEMPLATES: CompetitionTemplate[] = [
  template('football', {
    label: 'Football',
    description: 'Classic league table with wins, draws, losses, goals for and against.',
    competition_type: 'sports',
    supports_draws: true,
    score_label: 'Goals',
    scored_stat_key: 'goals_for',
    allowed_stat_key: 'goals_against',
    default_points_for_win: 3,
    default_points_for_draw: 1,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'goals_for', 'goals_against', 'played', 'goal_difference'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'goals_for', 'goals_against', 'goal_difference', 'points'],
    ranking_rules: [
      { criterion_type: 'statistic', statistic_key: 'points', label: 'Points', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'goal_difference', label: 'Goal Difference', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'goals_for', label: 'Goals For', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  }),
  template('basketball', {
    label: 'Basketball',
    description: 'Standings driven by win percentage and scoring difference.',
    competition_type: 'sports',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    statistic_keys: ['points', 'wins', 'losses', 'points_scored', 'points_allowed', 'played', 'point_difference', 'win_percentage'],
    standings_column_keys: ['played', 'wins', 'losses', 'points_scored', 'points_allowed', 'point_difference', 'win_percentage', 'points'],
    ranking_rules: [
      { criterion_type: 'statistic', statistic_key: 'win_percentage', label: 'Win Percentage', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'point_difference', label: 'Point Difference', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'points_scored', label: 'Points Scored', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  }),
  template('volleyball', {
    label: 'Volleyball',
    description: 'Track set wins/losses with set difference tiebreakers.',
    competition_type: 'sports',
    score_label: 'Sets',
    scored_stat_key: 'sets_won',
    allowed_stat_key: 'sets_lost',
    statistic_keys: ['points', 'wins', 'losses', 'sets_won', 'sets_lost', 'played', 'set_difference'],
    standings_column_keys: ['played', 'wins', 'losses', 'sets_won', 'sets_lost', 'set_difference', 'points'],
    ranking_rules: [
      { criterion_type: 'statistic', statistic_key: 'points', label: 'Points', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'set_difference', label: 'Set Difference', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'sets_won', label: 'Sets Won', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  }),
  template('cricket', {
    label: 'Cricket',
    description: 'Use league points with runs scored and allowed.',
    competition_type: 'sports',
    score_label: 'Runs',
    scored_stat_key: 'runs',
    allowed_stat_key: 'runs_allowed',
    supports_draws: true,
    default_points_for_win: 2,
    default_points_for_draw: 1,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'runs', 'runs_allowed', 'played'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'runs', 'runs_allowed', 'points'],
  }),
  template('rugby', {
    label: 'Rugby',
    description: 'Team standings driven by wins and scoring difference.',
    competition_type: 'sports',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    supports_draws: true,
    default_points_for_win: 4,
    default_points_for_draw: 2,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'points_scored', 'points_allowed', 'played', 'point_difference'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'points_scored', 'points_allowed', 'point_difference', 'points'],
  }),
  template('baseball', {
    label: 'Baseball',
    description: 'Track wins and run difference.',
    competition_type: 'sports',
    score_label: 'Runs',
    scored_stat_key: 'runs',
    allowed_stat_key: 'runs_allowed',
    statistic_keys: ['points', 'wins', 'losses', 'runs', 'runs_allowed', 'played', 'point_difference', 'win_percentage'],
    standings_column_keys: ['played', 'wins', 'losses', 'runs', 'runs_allowed', 'point_difference', 'win_percentage', 'points'],
    ranking_rules: [
      { criterion_type: 'statistic', statistic_key: 'win_percentage', label: 'Win Percentage', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'point_difference', label: 'Run Difference', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'runs', label: 'Runs', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  }),
  template('hockey', {
    label: 'Hockey',
    description: 'Goals, goal difference, and standings points.',
    competition_type: 'sports',
    supports_draws: true,
    score_label: 'Goals',
    scored_stat_key: 'goals_for',
    allowed_stat_key: 'goals_against',
    default_points_for_win: 2,
    default_points_for_draw: 1,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'goals_for', 'goals_against', 'played', 'goal_difference'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'goals_for', 'goals_against', 'goal_difference', 'points'],
  }),
  template('table_tennis', {
    label: 'Table Tennis',
    description: 'Set-based league table for individual or doubles play.',
    competition_type: 'sports',
    entity_type: 'individual',
    score_label: 'Sets',
    scored_stat_key: 'sets_won',
    allowed_stat_key: 'sets_lost',
    statistic_keys: ['points', 'wins', 'losses', 'sets_won', 'sets_lost', 'played', 'set_difference'],
    standings_column_keys: ['played', 'wins', 'losses', 'sets_won', 'sets_lost', 'set_difference', 'points'],
  }),
  template('tennis', {
    label: 'Tennis',
    description: 'Set-based standings for tennis ladders and leagues.',
    competition_type: 'sports',
    entity_type: 'individual',
    score_label: 'Sets',
    scored_stat_key: 'sets_won',
    allowed_stat_key: 'sets_lost',
    statistic_keys: ['points', 'wins', 'losses', 'sets_won', 'sets_lost', 'played', 'set_difference'],
    standings_column_keys: ['played', 'wins', 'losses', 'sets_won', 'sets_lost', 'set_difference', 'points'],
  }),
  template('chess', {
    label: 'Chess',
    description: 'Individual standings with wins, draws, losses, and points.',
    competition_type: 'education',
    entity_type: 'individual',
    supports_draws: true,
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    default_points_for_win: 1,
    default_points_for_draw: 0.5,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'played'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'points'],
  }),
  template('esports', {
    label: 'Esports',
    description: 'Wins and kill difference for league-style esports competitions.',
    competition_type: 'gaming',
    score_label: 'Kills',
    scored_stat_key: 'kills',
    allowed_stat_key: 'deaths',
    statistic_keys: ['points', 'wins', 'losses', 'kills', 'deaths', 'played', 'kill_death_ratio'],
    standings_column_keys: ['played', 'wins', 'losses', 'kills', 'deaths', 'kill_death_ratio', 'points'],
    ranking_rules: [
      { criterion_type: 'statistic', statistic_key: 'points', label: 'Points', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'kill_death_ratio', label: 'Kill/Death Ratio', direction: 'desc' },
      { criterion_type: 'statistic', statistic_key: 'kills', label: 'Kills', direction: 'desc' },
      { criterion_type: 'alphabetical', statistic_key: null, label: 'Alphabetical', direction: 'asc' },
    ],
  }),
  template('racing', {
    label: 'Racing',
    description: 'Season standings by race wins and points scored.',
    competition_type: 'sports',
    entity_type: 'individual',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    default_points_for_win: 25,
    default_points_for_draw: 0,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'losses', 'points_scored', 'played', 'average_points'],
    standings_column_keys: ['played', 'wins', 'losses', 'average_points', 'points'],
  }),
  template('swimming', {
    label: 'Swimming',
    description: 'Event standings using points from race results.',
    competition_type: 'fitness',
    entity_type: 'individual',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    default_points_for_win: 10,
    default_points_for_draw: 0,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'losses', 'points_scored', 'played', 'average_points'],
    standings_column_keys: ['played', 'wins', 'losses', 'average_points', 'points'],
  }),
  template('athletics', {
    label: 'Athletics',
    description: 'Track event wins and league points over multiple meets.',
    competition_type: 'fitness',
    entity_type: 'individual',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    default_points_for_win: 10,
    default_points_for_draw: 0,
    default_points_for_loss: 0,
    statistic_keys: ['points', 'wins', 'losses', 'points_scored', 'played', 'average_points'],
    standings_column_keys: ['played', 'wins', 'losses', 'average_points', 'points'],
  }),
  template('custom', {
    label: 'Custom',
    description: 'Start from a flexible league table and adjust the columns and ranking rules.',
    competition_type: 'custom',
    score_label: 'Points',
    scored_stat_key: 'points_scored',
    allowed_stat_key: 'points_allowed',
    statistic_keys: ['points', 'wins', 'draws', 'losses', 'points_scored', 'points_allowed', 'played', 'point_difference'],
    standings_column_keys: ['played', 'wins', 'draws', 'losses', 'points_scored', 'points_allowed', 'point_difference', 'points'],
    supports_draws: true,
    default_points_for_win: 3,
    default_points_for_draw: 1,
    default_points_for_loss: 0,
  }),
];

export function getCompetitionTemplate(templateKey: CompetitionTemplateKey): CompetitionTemplate {
  return COMPETITION_TEMPLATES.find((templateItem) => templateItem.key === templateKey) || COMPETITION_TEMPLATES[0];
}

export function getStatisticDefinition(statisticKey: string) {
  return STATISTICS_REGISTRY.find((statistic) => statistic.key === statisticKey);
}